export const labels = {
  common: {
    actions: "Actions",
    view: "View",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    create: "Create",
    update: "Update",
    login: "Login",
    logout: "Logout",
    password: "Password",
    signIn: "Sign In",
    forgotPassword: "Forgot Password?",
    loading: "Loading...",
    noData: "No data available",
    search: "Search...",
    status: "Status",
    date: "Date",
    name: "Name",
    email: "Email",
    role: "Role",
    type: "Type",
    staffName: "Super Admin",
    staffLevel: "Level 4 Moderator",
  },
  sidebar: {
    dashboard: "Dashboard",
    users: "Users",
    posts: "Posts",
    allPosts: "All Posts",
    comments: "Comments",
    streams: "Live Streams",
    activeStreams: "Active Streams",
    scheduledStreams: "Scheduled Streams",
    pastStreams: "Past Streams",
    reports: "Reports",
    moderationLogs: "Moderation Logs",
    analytics: "Analytics",
    settings: "Settings",
    appConfig: "App Config",
    rolesPermissions: "Roles & Permissions",
    notifications: "Notifications",
  },
  dashboard: {
    welcome: "Welcome back, Admin",
    overview: "Overview",
    totalUsers: "Total Users",
    activeStreams: "Active Streams",
    pendingReports: "Pending Reports",
    revenue: "Estimated Revenue",
    recentActivity: "Recent Activity",
  },
  users: {
    title: "User Management",
    block: "Block",
    unblock: "Unblock",
    deleteConfirm: "Are you sure you want to delete this user?",
    blockConfirm: "Are you sure you want to block this user?",
  },
  posts: {
    title: "Post Management",
    commentsTitle: "Comment Moderation",
    hide: "Hide",
    unhide: "Unhide",
  },
  streams: {
    activeTitle: "Active Streams",
    scheduledTitle: "Scheduled Streams",
    pastTitle: "Past Streams",
    stop: "Stop Stream",
    warn: "Warn Streamer",
    cancel: "Cancel Stream",
  },
  reports: {
    title: "Moderation Queue",
    resolve: "Resolve",
    dismiss: "Dismiss",
  },
  settings: {
    title: "Settings",
    appConfig: "Application Configuration",
    roles: "Roles & Permissions",
    notifications: "Notification Settings",
  }
};
